fix #114 見採点の回答があってもなにも表示されていない
ictsc/ictsc-rikka pull request #115
Opened 2023-02-27 20:47 UTC by x86taka

fix 114

2023-02-27 20:48 UTC, x86taka commented
参加者側のresponseに問題がないか未確認なので、確認していただけると助かります

2023-02-28 00:42 UTC, K-shir0 requested changes
採点されてない回答もカウントされるみたいです。ここを修正すれば動くと思います。

2023-02-28 00:42 UTC, K-shir0 commented on pkg/service/problem.go
>  		}
採点がされていない場合にカウントする必要があると思います！この状態だと常にカウントされてそうなので以下のような感じに直していただけると正しく動作するかと！
```go
	for _, answer := range answers {
		// 20分制約によって回答が見れていない場合
		if !IsfullAccess && !now.After(answer.CreatedAt.Add(s.uncheckedOverdueThreshold)) {
			continue
		}

		// 採点がされていない
		if answer.Point == nil {
// 以下に移動
			unchecked += 1

			if now.After(answer.CreatedAt.Add(s.uncheckedNearOverdueThreshold)) {
				uncheckedNearOverdue += 1
			}

			if now.After(answer.CreatedAt.Add(s.uncheckedOverdueThreshold)) {
				uncheckedOverdue += 1
			}

			continue
		}

// 以下略
```

2023-02-28 01:14 UTC, x86taka commented on pkg/service/problem.go
>  		}
@K-shir0 お願いします!

2023-02-28 01:56 UTC, K-shir0 approved these changes
動作確認しました！バッチリでした！！LGTM！

2023-02-28 02:02 UTC, merged