Feature/growi sync system
ictsc/ictsc-rikka pull request #99
Opened 2023-01-13 02:15 UTC by K-shir0

## 主な変更

- Growi の問題文を同期するシステムを作成

## XX

- Slack に通知する機能を別のPRで追加
- 削除は誤作動すると影響が大きいため追加と更新のみ対応

2023-01-13 02:17 UTC, K-shir0 commented
```
growi:
  url: <GrowiのURL>
  token: <Growiで生成したトークン>
  path: <Growiの問題文のあるパス 例: /a> 
  username: <Growiのユーザ>
  password: <Growiのパスワード>
```

こんな感じのを追加

```markdown
---
code: aaa
title: 問題タイトル
point: 100
solvedCriterion: 100
authorId: b8989948-05db-4b1c-ad5d-e6cadc96e798
---

# 問題タイトル 
```

2023-01-21 13:15 UTC, onokatio requested changes

2023-01-21 13:15 UTC, onokatio commented on pkg/service/growi_problem_sync.go
> +		err = doLogin(*s.u, *s.client, s.username, s.password, csrfToken)
ユーザー名・パスワードじゃなくてAPIキーだけでgrowiのAPI叩けたりしませんか？

2023-02-11 10:15 UTC, K-shir0 commented on pkg/repository/growi/page.go
> +type PageRepository struct {
1. GrowiRepository だとパッケージ名の repository/growi と干渉する
2. GrowiPageRepository だと repository/growi/growi_page_repository だとパッケージ名が func (例: GrowiPageRepository) に来てしまうので page_repository にすると不自然そう

なので競合したらしたでよさそう可能性は低いと思うので

2023-02-11 10:15 UTC, K-shir0 commented on pkg/service/growi_problem_sync.go
> +		err = doLogin(*s.u, *s.client, s.username, s.password, csrfToken)
いろいろ試したんですがユーザパスでログインしないと API が叩けないという仕様っぽいです

2023-02-11 10:33 UTC, K-shir0 commented
> thresholdの方がわかりやすい気がする Problem の方に揃えました

2023-02-24 13:12 UTC, onokatio approved these changes
LGTM

2023-02-25 07:54 UTC, merged